api_hash: your_api_hash
api_id: your_api_id
chat_infos:
- id: telegram_chat_id
  last_message: 0
  name: folder_name
  retry_ids: []
chat_source: 0
file_formats:
  audio:
  - all
  document:
  - all
  video:
  - all
media_types:
- audio
- photo
- video
- document
- voice
- video_note
